services:
    db:
        image: antonsiomchen/cheminfo-rdkit:rocky9-postgres16.11-rdkit2024.03.6
        environment:
            - POSTGRES_PASSWORD=anton
            - POSTGRES_USER=anton
            - POSTGRES_DB=anton
        ports:
            - "5432:5432"
        volumes:
            - ./init-molecules.sql:/docker-entrypoint-initdb.d/init-molecules.sql

# # volume is external
# volumes:
#     data:
